// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:97ec7c46-94fc-4287-9cb5-5bfbcd91eeec",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_MnDMsYwT9",
    "aws_user_pools_web_client_id": "5k82ji90ljrcsfend3eg8euphm",
    "oauth": {}
};


export default awsmobile;
