# Generated by Django 2.1.2 on 2018-10-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='numAttend',
            field=models.IntegerField(default=0),
        ),
    ]
