# Generated by Django 2.1.2 on 2018-11-21 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alumni_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='attended',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Event'),
        ),
    ]
