# Generated by Django 2.1.2 on 2018-11-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20181121_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_fName',
            field=models.CharField(help_text='Enter your first name', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_lName',
            field=models.CharField(help_text='Enter your last name', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_major',
            field=models.CharField(help_text='Enter your major', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_school',
            field=models.CharField(help_text='Enter school graduated from', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_yearGrad',
            field=models.PositiveSmallIntegerField(help_text='Enter graduation year', null=True),
        ),
    ]
